binary_search_improved.exe: binary_search_improved.o
	g++ -o binary_search_improved.exe binary_search_improved.o
binary_search_improved.o: binary_search_improved.cpp
	g++ -g -c binary_search_improved.cpp
