quick_sort: quick_sort.o insertion_sort.o
	g++ -o quick_sort quick_sort.o insertion_sort.o
quick_sort.o: quick_sort.cpp
	g++ -c quick_sort.cpp
insertion_sort.o: insertion_sort.cpp
	g++ -c insertion_sort.cpp
