indirect_inplace_quick_sort.exe: indirect_inplace_quick_sort.o
	g++ -g -o indirect_inplace_quick_sort.exe indirect_inplace_quick_sort.o
indirect_inplace_quick_sort.o: indirect_inplace_quick_sort.cpp
	g++ -g -c indirect_inplace_quick_sort.cpp
